CONEXION=main.dao.secuencialbd.ConexionSqlDAO
EQUIPO=main.dao.secuencialbd.EquipoSqlDAO
TIPOCABLE=main.dao.secuencialbd.TipoCableSqlDAO
TIPOEQUIPO=main.dao.secuencialbd.TipoEquipoSqlDAO
TIPOPUERTO=main.dao.secuencialbd.TipoPuertoSqlDAO
UBICACION=main.dao.secuencialbd.UbicacionSqlDAO